version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"    # Changed from 80:80 to 3000:80
    env_file:
      - frontend/.env.production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # This stays the same
    env_file:
      - backend/.env.production
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
